server:
  port : 8080

eureka:
  client:
    register-with-eureka: true  #是否要注册到其他Server上
    fetch-registry: true        #是否需要拉取服务信息
    service-url:
      defaultZone : http://localhost:7001/eureka/

zuul:
  routes:
    sbService :
      path : /sbService/**
      serviceId : spring-boot-service
